name: Cypress Tests

on:
  push:
    branches:
      - main  # Ejecutar en cada push a la rama main
  # schedule:
  #   - cron: '0 11-18 * * *'  # Ejecutar cada hora desde las 8 a.m. hasta las 3 p.m. hora local de Argentina (11 a.m. a 6 p.m. UTC)

jobs:
  cypress-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Ejecutar en Linux y Windows
        browser: [chrome, firefox, electron]   # Ejecutar en Chrome y Firefox

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: ${{ matrix.browser }}
        # env:
        #   CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
