name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.8.1'  # Especifica la versión de Node.js deseada

    - name: Install Cypress
      run: npm install cypress

    - name: Run Cypress tests
      run: |
        $(npm bin)/cypress run --headless
