name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '16'  # Especifica la versión de Node.js deseada

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run --headless
